apiVersion: batch/v1
kind: CronJob
metadata:
  name: mod-2-hi
spec:
  schedule: "* * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hi
            image: %%__IMAGE__%%
            imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure
