apiVersion: batch/v1
kind: CronJob
metadata:
  name: mod-2-hi
spec:
  schedule: "* * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hi
            image: daianatest.azurecr.io/shinbero/hello-world/mod_2:2021-10-05_06-55-50-UTC-278c2d18cafe262bd34419dd5eee86daafe1050b
            imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure
