apiVersion: batch/v1
kind: CronJob
metadata:
  name: mod-2-hi
spec:
  schedule: "* * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hi
            image: daianatest.azurecr.io/shinbero/hello-world/mod_2:2021-10-03_15-11-08-UTC-9e92bd2900cf308d0fc803ebfff5c4c2c0c5010e
            imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure
